version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "glue-job-tracker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o12gg65930r2"
s3_prefix = "glue-job-tracker"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GlueJobWorkerLimit=\"10\" GlueJobTimeoutLimit=\"480\" GlueJobNotifications=\"hamltm@amazon.com\""
image_repositories = []
